name: biologPlugin
version: '1.0-SNAPSHOT'
main: org.maks.biologPlugin.BiologPlugin
api-version: '1.20'
commands:
  biolog:
    description: Open biologist menu
    permission: biolog.use
  biologadmin:
    description: Edit biologist quest rewards
    permission: biolog.admin
permissions:
  biolog.use:
    description: Allows using /biolog
    default: op
  biolog.admin:
    description: Allows using /biologadmin
    default: op
